"use strict";
const KEY="mg-project-passport-v1";
const modules=[
 {title:"Найдите точку изменения",short:"Социальный заказ",intro:"Сначала отделите реальную потребность подростков от общего желания сделать занятие интереснее.",brief:"Ваша задача — сформулировать проблему через человека, доказательство и желаемое изменение.",render:one},
 {title:"Проверьте гипотезу",short:"Исследование",intro:"Не принимайте игровую механику на веру: выберите вопрос, способ проверки и измеримый показатель.",brief:"Сравните состояние до и после игры. Отмечайте только то, что действительно сможете проверить.",render:two},
 {title:"Соберите команду ИИ",short:"ИИ и критика",intro:"Используйте ИИ как аналитика и проектировщика, но оставьте проверку фактов за человеком.",brief:"Каждый запрос должен иметь роль, одну задачу, ограничения и критерий проверки.",render:three},
 {title:"Спроектируйте цифровой продукт",short:"Решение",intro:"Превратите идею в минимальный продукт, который помогает пройти конкретный повторяющийся процесс.",brief:"Не пытайтесь сделать всё сразу. Выберите три функции, без которых решение не работает.",render:four},
 {title:"Запустите пилот",short:"Пилот",intro:"Пилот — это ограниченная проверка в реальной ситуации, а не презентация готовой идеи.",brief:"Задайте площадку, срок, охват, ответственного и заранее решите, какой факт позволит продолжить проект.",render:five},
 {title:"Закройте дело",short:"Итоговый паспорт",intro:"Соберите цельную цепочку: заказ → проблема → причина → решение → изменение → эффект.",brief:"Итоговый паспорт можно скачать, распечатать и использовать для согласования пилота.",render:six}
];
let data=load(), current=Number(data._module||0);
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return {}}}
function save(){data._module=current;localStorage.setItem(KEY,JSON.stringify(data));document.querySelector("#save-state").textContent="Сохранено только на этом устройстве";updateProgress()}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function field(key,label,placeholder="",full=false){return `<div class="field ${full?"full":""}"><label for="${key}">${label}</label><textarea id="${key}" data-key="${key}" placeholder="${placeholder}">${esc(data[key])}</textarea></div>`}
function input(key,label,placeholder=""){return `<div class="field"><label for="${key}">${label}</label><input id="${key}" data-key="${key}" value="${esc(data[key])}" placeholder="${placeholder}"></div>`}
function choices(key,items){return `<div class="choice-grid">${items.map((x,i)=>`<div class="choice"><input id="${key}-${i}" type="radio" name="${key}" data-key="${key}" value="${esc(x)}" ${data[key]===x?"checked":""}><label for="${key}-${i}">${x}</label></div>`).join("")}</div>`}
function shell(m,body){return `<div class="module-content"><div class="module-head"><div><p class="eyebrow">Этап ${current+1} из ${modules.length}</p><h2>${m.title}</h2></div><div class="module-number">0${current+1}</div></div><p class="lead">${m.intro}</p><div class="brief">${m.brief}</div>${body}</div>`}
function one(){return shell(modules[0],`<h3>Кто должен почувствовать изменение?</h3>${choices("target",["Учащиеся 9–11 классов","Студенты СПО","Педагоги и музейные группы"])}<div class="field-grid">${field("need","Потребность или затруднение","Например: тема воспринимается как обязательная, но далёкая",true)}${field("evidence","Чем это подтверждается?","Опрос, наблюдение, запрос педагога — укажите источник",true)}${field("future","Как должно стать?","Опишите наблюдаемое изменение через 1–3 года",true)}</div><p class="eyebrow">Проверка этапа</p><div class="check-list"><label><input type="checkbox" data-key="fact" ${data.fact?"checked":""}> Проблема подтверждена конкретным наблюдением</label><label><input type="checkbox" data-key="boundary" ${data.boundary?"checked":""}> Я понимаю, что могу изменить самостоятельно</label></div>`)}
function two(){return shell(modules[1],`<h3>Что проверяем?</h3>${input("question","Исследовательский вопрос","Какая механика помогает запоминать факты?")}<div class="field-grid">${input("sample","Кого пригласите в проверку","Например: 30 учащихся 14–17 лет")}${input("period","Где и когда","Площадка и период пилота")}${input("baseline","Базовый показатель","Например: 48% правильных ответов до игры")}${input("targetMetric","Целевой показатель","Например: 75% после игры")}</div><h3>Выберите способы проверки</h3><div class="check-list"><label><input type="checkbox" data-key="methodTest" ${data.methodTest?"checked":""}> Тест до и после игры</label><label><input type="checkbox" data-key="methodGroup" ${data.methodGroup?"checked":""}> Фокус-группа или короткое интервью</label><label><input type="checkbox" data-key="methodObserve" ${data.methodObserve?"checked":""}> Наблюдение за первыми 15 минутами</label></div>${field("finding","Что уже показала проверка?","Отделите данные от предположений",true)}`)}
function three(){return shell(modules[2],`<h3>Выберите роли для ИИ</h3><div class="check-list"><label><input type="checkbox" data-key="aiAnalyst" ${data.aiAnalyst?"checked":""}> Аналитик — проверяет связь проблемы, причин, действий и результата</label><label><input type="checkbox" data-key="aiDesigner" ${data.aiDesigner?"checked":""}> Проектировщик — предлагает три различающихся решения</label><label><input type="checkbox" data-key="aiCritic" ${data.aiCritic?"checked":""}> Критик — ищет риски, альтернативные причины и нежелательные последствия</label><label><input type="checkbox" data-key="aiEditor" ${data.aiEditor?"checked":""}> Редактор — готовит документ только по проверенным материалам</label></div>${field("aiTask","Одна задача для ИИ","Например: найти разрывы в логике проекта",true)}${field("humanCheck","Что проверю сам(а)?","Факты, даты, полномочия, безопасность, понятность",true)}`)}
function four(){return shell(modules[3],`<h3>Минимальная рабочая версия</h3>${choices("product",["Интерактивная браузерная игра","Панель организатора и статистика","Методический цифровой навигатор"])}<div class="field-grid">${field("userProcess","Пользователь и процесс","Кто входит, что делает сейчас и где возникает барьер",true)}${field("scenario","Сценарий после улучшения","Как пользователь входит → действует → получает результат",true)}${field("functions","Три обязательные функции","1) ...\n2) ...\n3) ...",true)}${field("notNow","Что сознательно не входит в первую версию","Функции, которые отложены",true)}${field("data","Какие данные собираются","Например: псевдоним, время, баллы, ответы — без лишних персональных данных",true)}${field("ready","Критерий готовности","Полный сценарий на тестовых данных без критической ошибки",true)}</div>`)}
function five(){return shell(modules[4],`<div class="field-grid">${input("place","Площадка и территория","Музей, класс, колледж")}${input("pilotAudience","Сегмент и охват","Например: 3 группы по 10 человек")}${input("start","Начало пилота","Дата")}${input("end","Завершение пилота","Дата")}${field("exclude","Что не входит в пилот","Например: масштабирование на весь регион",true)}${field("roles","Владелец и исполнители","Кто отвечает за результат и кто помогает",true)}</div><h3>Дорожная карта</h3><div class="roadmap">${[1,2,3,4].map(i=>`<div class="roadmap-row"><b>${i}</b><input data-key="step${i}" value="${esc(data[`step${i}`])}" placeholder="Действие и проверяемый результат"><input data-key="owner${i}" value="${esc(data[`owner${i}`])}" placeholder="Ответственный"></div>`).join("")}</div>${field("decision","Как примем решение после пилота?","Продолжить, переработать, остановить или масштабировать — по каким фактам?",true)}`)}
function six(){let rows=[['Социальный заказ','target + need'],['Проблема и доказательство','need + evidence'],['Решение','product + functions'],['Пилот','place + pilotAudience + start + end'],['Критерий успеха','targetMetric + decision']];return shell(modules[5],`<div class="review">${rows.map(([label,keys])=>`<div class="review-item"><strong>${label}</strong>${keys.split(" + ").map(k=>esc(data[k])).filter(Boolean).join(" · ")||"Заполните предыдущие этапы"}</div>`).join("")}</div><h3>Название итогового проекта</h3>${input("projectTitle","Название","Операция: «Молодая гвардия» — интерактивный паспорт проекта")}<p id="finish-message" class="success"></p><button class="download" id="download-button" type="button">↓ Скачать паспорт проекта (.txt)</button><button class="download" id="print-button" type="button"> · Распечатать / сохранить в PDF</button>`)}
function render(){document.querySelector("#module-nav").innerHTML=modules.map((m,i)=>`<button class="${i===current?"active ":""}${done(i)?"done":""}" data-module="${i}"><b>0${i+1}</b><small>${m.short}</small></button>`).join("");document.querySelector("#module-content").innerHTML=modules[current].render();document.querySelector("#back-button").disabled=current===0;document.querySelector("#next-button").textContent=current===modules.length-1?"Сохранить паспорт":"Проверить этап →";bind();updateProgress();}
function done(i){return modules.slice(0,i+1).some(()=>false)||["target","question","aiTask","product","place","projectTitle"].some(k=>data[k])&&i===5}
function bind(){document.querySelectorAll("[data-key]").forEach(el=>el.addEventListener("input",()=>{data[el.dataset.key]=el.type==="checkbox"?el.checked:el.type==="radio"?(el.checked?el.value:data[el.dataset.key]):el.value;save()}));document.querySelectorAll("[data-module]").forEach(b=>b.addEventListener("click",()=>{current=Number(b.dataset.module);save();render()}));document.querySelector("#download-button")?.addEventListener("click",download);document.querySelector("#print-button")?.addEventListener("click",()=>print());}
function updateProgress(){let keys=["target","need","question","product","functions","place","decision","projectTitle"];let n=keys.filter(k=>data[k]&&String(data[k]).trim()).length;let p=Math.round(n/keys.length*100);document.querySelector("#progress-text").textContent=`${p}%`;document.querySelector("#progress-bar").style.width=`${p}%`}
function next(){if(current<modules.length-1){current++;save();render()}else{document.querySelector("#finish-message").textContent="Паспорт собран. Его можно скачать или распечатать.";download()}}
function download(){let lines=["ПАСПОРТ ПРОЕКТА — ОПЕРАЦИЯ: «МОЛОДАЯ ГВАРДИЯ»","",...modules.map((m,i)=>`ЭТАП ${i+1}. ${m.title.toUpperCase()}\n${Object.entries(data).filter(([k])=>!k.startsWith("_")).map(([k,v])=>`${k}: ${v}`).join("\n")}`).join("\n\n")];let blob=new Blob([lines],{type:"text/plain;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="pasport-proekta-molodaya-gvardiya.txt";a.click();URL.revokeObjectURL(a.href)}
